### ISSUE TITLE
How to turn User admin?

### ISSUE THREAD

**Issue by coreilabs** [firebase/friendlypix-web#35]
I can't find in internet how to change my user to admin in friendly pix, can you help me?

**Comment by nicolasgarnier** [comment]
Sorry for the delay @coreilabs 

Just added some instructions for this: https://github.com/firebase/friendlypix-web/blob/master/README.md#admins

**Comment by LDD19** [comment]
@nicolasgarnier Hello, the instructions aren't very clear, where do you add the entry to? And I guess this error is related to it? 
```
Error: Error occurred while parsing your function triggers.
friendlypix-web-master/functions/markAdmins.js:74
const user = await admin.auth().getUserByEmail(adminEmail);
                 ^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ldd/quinditech/friendlypix-web-master/functions/index.js:73:31)
```

**Comment by nicolasgarnier** [comment]
OOps just fixed this error in https://github.com/firebase/friendlypix-web/commit/b0d9f25a773f591ab240947443820f5bd011a28d

Thanks for the catch

**Comment by nicolasgarnier** [comment]
You add the entries directly using the Database explorer in the app console.
