### ISSUE TITLE
firebase deploy issue

### ISSUE THREAD

**Issue by crypcoder** [firebase/friendlypix-web#50]
I am getting following error, even though I have run firebase-functions in functions folder several times:
OS: Windows 10
node.js version: v9.5.0

=========================================================
C:\> firebase deploy
!  functions: package.json indicates an outdated version of firebase-functions.
 Please upgrade using npm install --save firebase-functions@latest in your functions directory.

=== Deploying to 'sr-friendlypix'...

i  deploying database, storage, functions, hosting
i  database: checking rules syntax...
+  database: rules syntax for database sr-friendlypix is valid
i  storage: checking storage.rules for compilation errors...
+  storage: rules file storage.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  storage: uploading rules storage.rules...
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers. Please ensure you have the latest firebase-functions SDK by running "npm i --save firebase-functions@latest" inside your functions folder.

Error: Firebase config variables are not available. Please use the latest version of the Firebase CLI to deploy this function.
    at init (C:\Users\A\documents\github\friendlypix\web\functions\node_modules\firebase-functions\lib\config.js:51:15)
    at Object.config (C:\Users\A\documents\github\friendlypix\web\functions\node_modules\firebase-functions\lib\config.js:29:9)
    at Object.<anonymous> (C:\Users\A\documents\github\friendlypix\web\functions\index.js:20:31)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

**Comment by nicolasgarnier** [comment]
It looks like you need to update the version of the firebase-functions. Have you tried updating it? Run `npm install --save firebase-functions@latest` in the functions directory.
